idf_component_register(SRCS "salvar_nvs.c"
                            "bluetooth.c"
                            "config.c"
                            "lora.c"
                            "http_request.c"
                            "network_mode.c"
                            "wifi.c"
                            "main.c"
                    INCLUDE_DIRS ".")
